name: BetterCombat
version: '${project.version}'
main: me.tacnayn.bettercombat.BetterCombat
api-version: 1.18
authors: [ TacNayn ]
description: Implementation of an AoE attack system
depend:
  - ProtocolLib
libraries:
  - com.github.shynixn.structureblocklib:structureblocklib-bukkit-api:2.8.0
  - com.github.shynixn.structureblocklib:structureblocklib-bukkit-core:2.8.0
commands:
  testdungeongen:
    usage: /<command> <count>
    description: Test the dungeon generator
  setstat:
    usage: /<command> <type> <value>
    description: Set stat value for the held item
  copyworldfile:
    usage: /<command> <filename>
    description: Loads the world
  switchworlds:
    aliases:
      - swapworlds
      - goto
    usage: /<command> <world>
    description: Switches the player to another world
  loadworld:
    aliases: load
    usage: /<command> <world>
    description: Loads the world
  unloadworld:
    aliases: unload
    usage: /<command> <world>
    description: Unloads the world
  testpaste:
    usage: /<command> <x> <y> <z>
    description: Test the block paste system